require "config.options"
require "config.keymaps"
require "config.autocmds"
require "config.lsp"

require "plugins.todo-comments"
require "plugins.mini"
require "plugins.snacks"
require "plugins.yazi"
require "plugins.catppuccin"
require "plugins.conform"
require "plugins.codesnap"
require "plugins.treesitter"
require "plugins.lualine"
