import = ["/home/fveracoechea/.config/alacritty/catppuccin/catppuccin-mocha.toml"]
live_config_reload = false

[colors]
draw_bold_text_with_bright_colors = false

[env]
TERM = "xterm-256color"

[font]
size = 12

[font.bold]
family = "SauceCodePro Nerd Font"
style = "Bold"

[font.bold_italic]
family = "SauceCodePro Nerd Font"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "SauceCodePro Nerd Font"
style = "Italic"

[font.normal]
family = "SauceCodePro Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[window]
decorations = "Full"
dynamic_title = true
opacity = 1.0
# startup_mode = "Maximized"

[window.padding]
x = 4
y = 4

[selection]
save_to_clipboard = true
